const fs = require("fs");
const path = require("path");

// Read .env file
const envPath = path.join(__dirname, ".env");
if (!fs.existsSync(envPath)) {
  console.error(
    "❌ .env file not found. Please copy env.template to .env and update the values."
  );
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, "utf8");

// Parse .env file
const envVars = {};
envContent.split("\n").forEach((line) => {
  const trimmedLine = line.trim();
  if (trimmedLine && !trimmedLine.startsWith("#")) {
    const [key, ...valueParts] = trimmedLine.split("=");
    if (key && valueParts.length > 0) {
      const value = valueParts
        .join("=")
        .trim()
        .replace(/^["']|["']$/g, "");
      envVars[key.trim()] = value;
    }
  }
});

// Create env.js content
const envJSPath = path.join(__dirname, "js", "env.js");
let envJSContent = `/**
 * Environment Variables
 *
 * This file is automatically generated from .env file.
 * Do not edit this file directly - edit your .env file instead.
 */

export const STYTCH_PUBLIC_TOKEN = "{{STYTCH_PUBLIC_TOKEN}}";
`;

// Replace placeholders
envJSContent = envJSContent.replace(
  /{{STYTCH_PUBLIC_TOKEN}}/g,
  envVars.STYTCH_PUBLIC_TOKEN
);

// Write updated env file
fs.writeFileSync(envJSPath, envJSContent);
console.log("✅ Environment variables updated from .env file");
