import type { Metadata } from "next";
import "./globals.css";
import { createStytchB2BHeadlessClient } from "@stytch/nextjs/b2b/headless";
import { StytchB2BProvider } from "@stytch/nextjs/b2b";

export const metadata: Metadata = {
  title: "Next.js Example - Headless SDK",
  description: "Generated by create next app",
};

// Create the Stytch client
const stytch = createStytchB2BHeadlessClient(
  process.env.STYTCH_PUBLIC_TOKEN || "test-token-placeholder"
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StytchB2BProvider stytch={stytch}>{children}</StytchB2BProvider>
      </body>
    </html>
  );
}
