import type { Metadata } from "next";
import { Providers } from "@/components/Providers";
import { Page } from "@stytch-all-examples/internal";

export const metadata: Metadata = {
  title: "Next.js Example - Headless SDK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Page>{children}</Page>
        </Providers>
      </body>
    </html>
  );
}
